# Generated by Django 5.2.17 on 2026-10-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cloudinary_attachment_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_e67e01_idx',
            old_name='tasks_task_status_497867_idx',
        ),
    ]
